name: "${project.name}"
version: "${project.version}"
main: "${project.groupId}.Main"
softdepend: [Multiverse-Core]
website: https://github.com/erudosan0524-JP
author: 'erudo'
commands:
   eAntiTroll:
    description: kaijo/on/off
permissions:
  eantitroll.kaijo:
    default: op
  eantitroll.kidou:
    default: op
  eantitroll.lava:
    default: op
  eantitroll.admin:
    default: op