name: eBowSpleef
version: 0.0.2
main: com.github.erudo.ebowspleef.Main
website: https://github.com/erudosan0524-JP
author: 'Ld0'
commands:
   ebs:
    description: ebowSpleef
permissions:
  ebs.start:
    default: op