name: eOni2
version: 0.2.1
main: com.github.erudo0524.eoni2.Main
website: https://github.com/erudosan0524-JP
author: 'Ld0'
commands:
   eOni:
    description: onigokkoPlugin
permissions:
  eoni.start:
    default: op
  eoni.wp:
    default: op
  eoni.set.tp:
    default: op
  eoni.set.oni:
    default: op
  eoni.set.block:
    default: op
  eoni.set.chest:
    default: op
  eoni.version:
    default: true